version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis-1-basic
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ../1-basic-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    volumes:
      - ../cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: /data/load-redis.sh 1-basic
    networks:
      - backend
    depends_on:
      cache:
        condition: service_started

  redis-api:
    image: cs-t681-voter-api:v1
    container_name: voter-api-1
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=1-basic:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true