version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis-basic-1
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - backend
  redis-api:
    image: cs-t681-voter-api:v1
    container_name: voter-api-1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - cache
    environment:
      - REDIS_URL=1-basic:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true