version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis-1-basic
    ports:
      - 6379:6379
      - 8001:8001
  redis-api:
    image: cs-t681-voter-api:v1
    container_name: voter-api-1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - cache